import { create } from 'zustand';
import { Language } from '../types';

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    appName: 'DONATION HUB PRO',
    appTagline: 'Enterprise Donation Management & Audit Ledger',
    dashboard: 'Dashboard',
    analytics: 'Analytics & Charts',
    donationsDirectory: 'Donations Directory',
    expensesDirectory: 'Expenses Directory',
    reportsExcel: 'Reports & Excel Export',
    donationCategories: 'Donation Categories',
    receiptSettings: 'Receipt Settings',
    userManagement: 'User Management',
    auditLedger: 'System Audit Ledger',
    logout: 'Sign Out',
    recordNewDonation: 'Record New Donation',
    recordNewExpense: 'Record New Expense',
    exportExcelReport: 'Export Excel Report',
    receiptImages: 'Receipt Images (22×11 cm)',
    allCategories: 'All Purpose Categories',
    allStatuses: 'All Statuses',
    allPaymentModes: 'All Payment Modes',
    searchPlaceholder: 'Search donor name, receipt number, ID, or transaction ref...',
    viewDetails: 'View Details',
    downloadPdf: 'Download PDF',
    shareWhatsApp: 'Share WhatsApp',
    approve: 'Approve',
    reject: 'Reject',
    pending: 'PENDING',
    approved: 'APPROVED',
    rejected: 'REJECTED',
    totalCollection: 'Total Collection',
    totalExpenses: 'Total Expenses',
    netBalance: 'Net Fund Balance',
    donorName: 'Donor Name',
    amount: 'Amount',
    date: 'Date',
    receiptNo: 'Receipt No',
    paymentChannel: 'Payment Channel',
    saveSettings: 'Save & Apply Settings',
    navigation: 'Navigation Menu',
    executiveDashboard: 'Executive Financial Dashboard',
    recentDonations: 'Recent Approved Donations',
    recentExpenses: 'Recent Expense Claims',
    viewAllDonations: 'View All Donations',
    viewAllExpenses: 'View All Expenses',
    thisMonthOverview: 'This Month Overview',
    cash: 'Cash',
    upi: 'UPI',
    bankTransfer: 'Bank Transfer',
    cheque: 'Cheque',
    card: 'Card',
    category: 'Category / Purpose',
    actions: 'Actions',
    cancel: 'Cancel',
    save: 'Save',
    close: 'Close',
    addCategory: 'Add New Category',
    addUser: 'Add New User',
    role: 'Role',
    status: 'Status',
    notes: 'Notes / Remarks',
    mobileNumber: 'Mobile Number',
    transactionRef: 'Transaction Ref / UTR',
    purpose: 'Purpose Category',
    financialYear: 'Financial Year',
    uploadHeaderImage: 'Upload Header Image (22 × 2.5 cm)',
    uploadFooterImage: 'Upload Footer Image (22 × 2.0 cm)',
    orgName: 'Organization Name',
    orgAddress: 'Registered Address',
    orgMobile: 'Phone / Mobile',
    orgEmail: 'Email Address',
    livePdfPreview: 'Live 22 × 11 cm Receipt PDF Preview',
    confirmApprove: 'Are you sure you want to approve?',
    auditAction: 'Action Performed',
    auditUser: 'Performed By',
    auditTime: 'Timestamp',
  },
  hi: {
    appName: 'डोनेशन हब प्रो',
    appTagline: 'पारदर्शिता के साथ दान प्रबंधन',
    dashboard: 'मुख्य डैशबोर्ड',
    analytics: 'विश्लेषण एवं चार्ट',
    donationsDirectory: 'दान संग्रह निर्देशिका',
    expensesDirectory: 'खर्च निर्देशिका',
    reportsExcel: 'रिपोर्ट्स एवं एक्सेल निर्यात',
    donationCategories: 'दान की श्रेणियां',
    receiptSettings: 'रसीद लेआउट सेटिंग्स',
    userManagement: 'उपयोगकर्ता प्रबंधन',
    auditLedger: 'सिस्टम ऑडिट लेजर',
    logout: 'साइन आउट',
    recordNewDonation: 'नया दान दर्ज करें',
    recordNewExpense: 'नया खर्च दर्ज करें',
    exportExcelReport: 'एक्सेल रिपोर्ट डाउनलोड करें',
    receiptImages: 'रसीद छवियां (22×11 सेमी)',
    allCategories: 'सभी दान श्रेणियां',
    allStatuses: 'सभी स्थितियां',
    allPaymentModes: 'सभी भुगतान माध्यम',
    searchPlaceholder: 'दाता का नाम, रसीद नंबर, आईडी या संदर्भ खोजें...',
    viewDetails: 'विवरण देखें',
    downloadPdf: 'पीडीएफ डाउनलोड करें',
    shareWhatsApp: 'व्हाट्सएप शेयर करें',
    approve: 'स्वीकृत करें',
    reject: 'अस्वीकार करें',
    pending: 'लंबित (PENDING)',
    approved: 'स्वीकृत (APPROVED)',
    rejected: 'अस्वीकृत (REJECTED)',
    totalCollection: 'कुल दान संग्रह',
    totalExpenses: 'कुल खर्च',
    netBalance: 'शुद्ध शेष राशि',
    donorName: 'दाता का नाम',
    amount: 'राशि (₹)',
    date: 'दिनांक',
    receiptNo: 'रसीद संख्या',
    paymentChannel: 'भुगतान माध्यम',
    saveSettings: 'सेटिंग्स सहेजें',
    navigation: 'नेविगेशन मेनू',
    executiveDashboard: 'वित्तीय डैशबोर्ड',
    recentDonations: 'हाल के स्वीकृत दान',
    recentExpenses: 'हाल के खर्च',
    viewAllDonations: 'सभी दान देखें',
    viewAllExpenses: 'सभी खर्च देखें',
    thisMonthOverview: 'इस महीने का विवरण',
    cash: 'नकद (Cash)',
    upi: 'यूपीआई (UPI)',
    bankTransfer: 'बैंक ट्रांसफर',
    cheque: 'चेक (Cheque)',
    card: 'कार्ड (Card)',
    category: 'श्रेणी / उद्देश्य',
    actions: 'कार्रवाई',
    cancel: 'रद्द करें',
    save: 'सहेजें',
    close: 'बंद करें',
    addCategory: 'नई श्रेणी जोड़ें',
    addUser: 'नया उपयोगकर्ता जोड़ें',
    role: 'भूमिका (Role)',
    status: 'स्थिति',
    notes: 'टिप्पणी / विवरण',
    mobileNumber: 'मोबाइल नंबर',
    transactionRef: 'लेनदेन संदर्भ / UTR',
    purpose: 'दान उद्देश्य',
    financialYear: 'वित्तीय वर्ष',
    uploadHeaderImage: 'हेडर छवि अपलोड करें (22 × 2.5 सेमी)',
    uploadFooterImage: 'फुटर छवि अपलोड करें (22 × 2.0 सेमी)',
    orgName: 'संस्था का नाम',
    orgAddress: 'पंजीकृत पता',
    orgMobile: 'फोन / मोबाइल',
    orgEmail: 'ईमेल पता',
    livePdfPreview: 'लाइव 22 × 11 सेमी रसीद पीडीएफ पूर्वावलोकन',
    confirmApprove: 'क्या आप स्वीकृत करना चाहते हैं?',
    auditAction: 'कार्रवाई',
    auditUser: 'उपयोगकर्ता',
    auditTime: 'समय',
  },
  mr: {
    appName: 'डोनेशन हब प्रो',
    appTagline: 'पारदर्शकतेसह देणगी व्यवस्थापन',
    dashboard: 'मुख्य डॅशबोर्ड',
    analytics: 'विश्लेषण आणि आलेख',
    donationsDirectory: 'देणगी नोंदवही',
    expensesDirectory: 'खर्च नोंदवही',
    reportsExcel: 'अहवाल आणि एक्सेल एक्सपोर्ट',
    donationCategories: 'देणगी प्रकार / वर्ग',
    receiptSettings: 'पावती रचना सेटिंग्ज',
    userManagement: 'वापरकर्ता व्यवस्थापन',
    auditLedger: 'सिस्टम ऑडिट वही',
    logout: 'साइन आउट करा',
    recordNewDonation: 'नवीन देणगी नोंदवा',
    recordNewExpense: 'नवीन खर्च नोंदवा',
    exportExcelReport: 'एक्सेल अहवाल डाऊनलोड करा',
    receiptImages: 'पावती प्रतिमा (22×11 सेमी)',
    allCategories: 'सर्व देणगी प्रकार',
    allStatuses: 'सर्व स्थिती',
    allPaymentModes: 'सर्व पेमेंट पद्धती',
    searchPlaceholder: 'देणगीदाराचे नाव, पावती क्र., आयडी किंवा संदर्भ शोधा...',
    viewDetails: 'तपशील पहा',
    downloadPdf: 'पीडीएफ डाऊनलोड करा',
    shareWhatsApp: 'व्हॉट्सॲपवर शेअर करा',
    approve: 'मंजूर करा',
    reject: 'नाकारा',
    pending: 'प्रलंबित (PENDING)',
    approved: 'मंजूर (APPROVED)',
    rejected: 'नाकारले (REJECTED)',
    totalCollection: 'एकूण जमा रक्कम',
    totalExpenses: 'एकूण खर्च',
    netBalance: 'निव्वळ शिल्लक निधी',
    donorName: 'देणगीदाराचे नाव',
    amount: 'रक्कम (₹)',
    date: 'तारीख',
    receiptNo: 'पावती क्रमांक',
    paymentChannel: 'पेमेंटचा प्रकार',
    saveSettings: 'सेटिंग्ज जतन करा',
    navigation: 'नेव्हिगेशन मेनू',
    executiveDashboard: 'आर्थिक डॅशबोर्ड',
    recentDonations: 'अलीकडील मंजूर देणग्या',
    recentExpenses: 'अलीकडील खर्च',
    viewAllDonations: 'सर्व देणग्या पहा',
    viewAllExpenses: 'सर्व खर्च पहा',
    thisMonthOverview: 'या महिन्याचा तपशील',
    cash: 'रोख (Cash)',
    upi: 'यूपीआय (UPI)',
    bankTransfer: 'बँक ट्रान्सफर',
    cheque: 'धनादेश (Cheque)',
    card: 'कार्ड (Card)',
    category: 'देणगी वर्ग / हेतू',
    actions: 'कृती',
    cancel: 'रद्द करा',
    save: 'जतन करा',
    close: 'बंद करा',
    addCategory: 'नवीन वर्ग जोडा',
    addUser: 'नवीन वापरकर्ता जोडा',
    role: 'भूमिका',
    status: 'स्थिती',
    notes: 'टिपण / तपशील',
    mobileNumber: 'मोबाईल नंबर',
    transactionRef: 'व्यवहार संदर्भ / UTR',
    purpose: 'देणगी हेतू',
    financialYear: 'आर्थिक वर्ष',
    uploadHeaderImage: 'हेडर प्रतिमा अपलोड करा (22 × 2.5 सेमी)',
    uploadFooterImage: 'फुटर प्रतिमा अपलोड करा (22 × 2.0 सेमी)',
    orgName: 'संस्थेचे नाव',
    orgAddress: 'नोंदणीकृत पत्ता',
    orgMobile: 'फोन / मोबाईल',
    orgEmail: 'ईमेल पत्ता',
    livePdfPreview: 'लाइव्ह 22 × 11 सेमी पावती पूर्वदृश्य',
    confirmApprove: 'तुम्हाला मंजूर करायचे आहे का?',
    auditAction: 'कृती',
    auditUser: 'वापरकर्ता',
    auditTime: 'वेळ',
  },
  gu: {
    appName: 'ડોનેશન હબ પ્રો',
    appTagline: 'પારદર્શિતા સાથે દાન સંચાલન',
    dashboard: 'ડેશબોર્ડ',
    analytics: 'વિશ્લેષણ અને ચાર્ટ્સ',
    donationsDirectory: 'દાન સંગ્રહ',
    expensesDirectory: 'ખર્ચ',
    reportsExcel: 'અહેવાલો અને એક્સેલ નિકાસ',
    donationCategories: 'દાન શ્રેણીઓ',
    receiptSettings: 'રસીદ લેઆઉટ સેટિંગ્સ',
    userManagement: 'વપરાશકર્તા સંચાલન',
    auditLedger: 'સિસ્ટમ ઓડિટ લોગ',
    logout: 'લૉગ આઉટ',
    recordNewDonation: 'નવું દાન ઉમેરો',
    recordNewExpense: 'નવો ખર્ચ ઉમેરો',
    exportExcelReport: 'એક્સેલ અહેવાલ નિકાસ કરો',
    receiptImages: 'રસીદ છબીઓ (22×11 સેમી)',
    allCategories: 'તમામ શ્રેણીઓ',
    allStatuses: 'તમામ સ્થિતિઓ',
    allPaymentModes: 'તમામ મોડ્સ',
    searchPlaceholder: 'દાતાનું નામ, રસીદ નંબર, આઈડી શોધો...',
    viewDetails: 'વિગતો જુઓ',
    downloadPdf: 'પીડીએફ ડાઉનલોડ કરો',
    shareWhatsApp: 'વોટ્સએપ શેર કરો',
    approve: 'મંજૂર કરો',
    reject: 'નામંજૂર કરો',
    pending: 'પેન્ડિંગ',
    approved: 'મંજૂર',
    rejected: 'નામંજૂર',
    totalCollection: 'કુલ સંગ્રહ',
    totalExpenses: 'કુલ ખર્ચ',
    netBalance: 'ચોખ્ખી બાકી રકમ',
    donorName: 'દાતાનું નામ',
    amount: 'રકમ (₹)',
    date: 'તારીખ',
    receiptNo: 'રસીદ નંબર',
    paymentChannel: 'ચુકવણી ચેનલ',
    saveSettings: 'સેટિંગ્સ સાચવો',
    navigation: 'નેવિગેશન મેનૂ',
    executiveDashboard: 'નાણાકીય ડેશબોર્ડ',
    recentDonations: 'તાજેતરના મંજૂર દાન',
    recentExpenses: 'તાજેતરના ખર્ચ',
    viewAllDonations: 'તમામ દાન જુઓ',
    viewAllExpenses: 'તમામ ખર્ચ જુઓ',
    thisMonthOverview: 'આ મહિનાની વિગત',
    cash: 'રોકડ',
    upi: 'યુપીઆઈ',
    bankTransfer: 'બેંક ટ્રાન્સફર',
    cheque: 'ચેક',
    card: 'કાર્ડ',
    category: 'શ્રેણી',
    actions: 'ક્રિયાઓ',
    cancel: 'રદ કરો',
    save: 'સાચવો',
    close: 'બંધ કરો',
    addCategory: 'નવી શ્રેણી ઉમેરો',
    addUser: 'નવો વપરાશકર્તા ઉમેરો',
    role: 'ભૂમિકા',
    status: 'સ્થિતિ',
    notes: 'નોંધ',
    mobileNumber: 'મોબાઈલ નંબર',
    transactionRef: 'ટ્રાન્ઝેક્શન સંદર્ભ',
    purpose: 'હેતુ',
    financialYear: 'નાણાકીય વર્ષ',
    uploadHeaderImage: 'હેડર છબી અપલોડ કરો',
    uploadFooterImage: 'ફૂટર છબી અપલોડ કરો',
    orgName: 'સંસ્થાનું નામ',
    orgAddress: 'સરનામું',
    orgMobile: 'મોબાઈલ',
    orgEmail: 'ઈમેઈલ',
    livePdfPreview: 'રસીદ પીડીએફ પૂર્વાવલોકન',
    confirmApprove: 'મંજૂર કરવા માંગો છો?',
    auditAction: 'ક્રિયા',
    auditUser: 'વપરાશકર્તા',
    auditTime: 'સમય',
  },
};

export const useLanguageStore = create<LanguageState>((set, get) => ({
  language: 'en',
  setLanguage: (language) => set({ language }),
  t: (key) => {
    const lang = get().language;
    return translations[lang]?.[key] || translations.en[key] || key;
  },
}));
